= Draft OGC API - Environmental Data Retrieval  Conformance Test Suite

== Scope

This executable test suite is for the http://docs.ogc.org/DRAFTS/19-086.html[OGC API - Environmental Data Retrieval (EDR API)] draft standard.

Visit the http://opengeospatial.github.io/ets-ogcapi-edr10/[project documentation website]
for more information, including the API documentation.


The implementation status of each abstract test is shown https://github.com/opengeospatial/ets-ogcapi-edr10/blob/master/teststatus.adoc[here].

== How to build the test suite

The test suite is built using https://maven.apache.org/[Apache Maven v3].

Step 1. First clone the repo.

`git clone https://github.com/opengeospatial/ets-ogcapi-edr10.git`

Step 2. Then navigate into the local repo.

`cd ets-ogcapi-edr10`

Step 3. Now clean the project.

`mvn clean`

Step 4. Now build the project.

`mvn package`

NOTE: On some operating systems, when building the ETS under Java 11+ for the first time, it may be necessary to run `mvn package` twice.

NOTE: Running `mvn package` will automatically update the jar file `ets-ogcapi-edr10-x.x-SNAPSHOT.jar` in the `/ets-ogcapi-edr10/docker/teamengine/WEB-INF/lib`. To disable this function, modify `maven-antrun-plugin` in the pom.xml file.

== How to run the test suite
The options for running the suite are summarized in

include::src/site/asciidoc/how-to-run-the-tests.adoc[]

== How to debug using docker

After running `mvn package`:

Navigate to the docker folder.

`cd /docker`

Build the docker image.

`docker build -t edr10:local . `

Run the docker image.

`docker run -p 9090:8080/tcp edr10:local`

Now visit http://localhost:9090/teamengine

Log into teamengine with username *developer* and password *developer*.

== How to contribute

If you would like to get involved, you can:

* https://github.com/opengeospatial/ets-ogcapi-edr10/issues[Report an issue] such as a defect or
an enhancement request
* Help to resolve an https://github.com/opengeospatial/ets-ogcapi-edr10/issues?q=is%3Aopen[open issue]
* Fix a bug: Fork the repository, apply the fix, and create a pull request
* Add new tests: Fork the repository, implement and verify the tests on a new topic branch,
and create a pull request (don't forget to periodically rebase long-lived branches so
there are no extraneous conflicts)
