= Draft OGC API - Environmental Data Retrieval  Conformance Test Suite

== Scope

This executable test suite is for the OGC API - Environmental Data Retrieval (EDR API) draft standard.

Visit the http://opengeospatial.github.io/ets-ogcapi-edr10/[project documentation website]
for more information, including the API documentation.

|===
|*Req. #* | *Identifier* | *Implemented in Java Class*

|1
|/req/core/api-common
|`org.opengis.cite.ogcapiedr10.landingpage.LandingPage`

|2
|/req/core/conformance
|`org.opengis.cite.ogcapiedr10.conformance.Conformance`
|===

The implementation status of each abstract test is shown http://opengeospatial.github.io/ets-ogcapi-edr10/teststatus.adoc[here].

== How to build the test suite

The test suite is built using https://maven.apache.org/[Apache Maven v3].

== How to run the test suite
The options for running the suite are summarized in

include::src/site/asciidoc/how-to-run-the-tests.adoc[]

== How to contribute

If you would like to get involved, you can:

* https://github.com/opengeospatial/ets-ogcapi-edr10/issues[Report an issue] such as a defect or
an enhancement request
* Help to resolve an https://github.com/opengeospatial/ets-ogcapi-edr10/issues?q=is%3Aopen[open issue]
* Fix a bug: Fork the repository, apply the fix, and create a pull request
* Add new tests: Fork the repository, implement and verify the tests on a new topic branch,
and create a pull request (don't forget to periodically rebase long-lived branches so
there are no extraneous conflicts)
