= OGC API - Environmental Data Retrieval 1.0 Conformance Test Suite

== Scope

This executable test suite (ETS) verifies that an implementation of the https://ogcapi.ogc.org/edr[OGC API - Environmental Data Retrieval] standard conforms to standard and related parts.

Conformance testing is a kind of "black box" testing that examines externally visible characteristics or behaviors of the implementation and is independent of any implementation details.

Several conformance classes are defined in the principal specifications. The ones
listed below are covered by this test suite:

* Core
* Collections
* JSON
* GeoJSON
* EDR GeoJSON
* Queries

== Test requirements

The documents listed below stipulate requirements that must be satisfied by a
conforming implementation.

1. https://docs.ogc.org/is/19-086r4/19-086r4.html[OGC API - Environmental Data Retrieval, version 1.0.0, specified in OGC 19-086r4]

There are some requirements the test suite expects to be satisfied by the service under test:

* General:
    - The API landing page response must be available in JSON.
    - The API definition response must be available in OpenAPI 3.0.
    - The conformance classes response must be available in JSON.
    - The collections metadata response and feature collection metadata responses must be available in JSON.
    - The collection metadata must declared the supported data_queries, parameter_names, output_formats, spatial extent, and temporal extent
    - Collections and query responses must be available in either CoverageJSON or GeoJSON.
    - The CRS84 (http://www.opengis.net/def/crs/OGC/1.3/CRS84) coordinate reference system must be supported.

== Test suite structure

The test suite definition file (testng.xml) is located in the root package,
`org.opengis.cite.ogcapiedr10`. A conformance class corresponds to a &lt;test&gt; element, each
of which includes a set of test classes that contain the actual test methods.
The general structure of the test suite is shown in Table 1.

.Test suite structure
[cols="2,6a",options=header]
|===
|Conformance class
|Test classes

|Core
|org.opengis.cite.ogcapiedr10.landingpage.*
|org.opengis.cite.ogcapiedr10.conformance.*
|org.opengis.cite.ogcapiedr10.corecollections.*

|Collections
|org.opengis.cite.ogcapiedr10.collections.*
|org.opengis.cite.ogcapiedr10.queries.*  

|JSON
|org.opengis.cite.ogcapiedr10.encodings.json.*

|GeoJSON
|org.opengis.cite.ogcapiedr10.encodings.geojson.*

|EDR GeoJSON
|org.opengis.cite.ogcapiedr10.encodings.edrgeojson.*

|===

The Javadoc documentation provides more detailed information about the test
methods that constitute the suite.

include::how-to-run-the-tests.adoc[]

== Using the REST API

Using the REST API of the TEAM Engine requires some run arguments. These ate summarized in Table 2.
The _Obligation_ descriptor can have the following values: M (mandatory), O (optional), or C (conditional).

.Test run arguments
[cols="1,1,1,6",options=header]
|===
|Name
|Value domain
|Obligation
|Description

|iut
|URI
|M
|A URI that refers to the implementation under test or metadata about it. Ampersand ('&amp;') characters must be percent-encoded as '%26'.

|apiDefinition
|A comma-separated list of string values.
|M
|A URI that refers to the API definition of the implementation under test.

|===
